[package]
name = "capnp-gj"
version = "0.0.0"
authors = ["David Renshaw <david@sandstorm.io>"]
license = "MIT"
description = "asynchronous I/O for Cap'n Proto"
repository = "https://github.com/dwrensha/capnp-gj"

keywords = ["async"]

[dependencies]
gj = "*"
capnp = "*"